
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: hackaton

test:
  <<: *default
  database: hackaton


production:
  <<: *default
  database: hackaton
  username: 
  password: <%= ENV['FASTSHOP_DATABASE_PASSWORD'] %>
